ALTER TABLE ASIGNATURA DROP FOREIGN KEY FK_ASIGNATURA_TITULACION_Codigo
ALTER TABLE CLASE DROP FOREIGN KEY FK_CLASE_ASIGNATURA_Referencia
ALTER TABLE CLASE DROP FOREIGN KEY FK_CLASE_GRUPO_ID
ALTER TABLE ENCUESTA DROP FOREIGN KEY FK_ENCUESTA_EXPEDIENTE_Numero_Expediente
ALTER TABLE EXPEDIENTE DROP FOREIGN KEY FK_EXPEDIENTE_TITULACION_Codigo
ALTER TABLE EXPEDIENTE DROP FOREIGN KEY FK_EXPEDIENTE_ALUMNO_ID
ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_GRUPO_ID
ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_TITULACION_Codigo
ALTER TABLE GRUPOSPORASIG DROP FOREIGN KEY FK_GRUPOSPORASIG_GRUPO_ID
ALTER TABLE GRUPOSPORASIG DROP FOREIGN KEY FK_GRUPOSPORASIG_ASIGNATURA_Referencia
ALTER TABLE MATRICULA DROP FOREIGN KEY FK_MATRICULA_EXPEDIENTE_Numero_Expediente
ALTER TABLE ASIGNATURA_MATRICULA DROP FOREIGN KEY FK_ASIGNATURA_MATRICULA_CURSOACADEMICO
ALTER TABLE ASIGNATURA_MATRICULA DROP FOREIGN KEY FK_ASIGNATURA_MATRICULA_ASIGNATURA_Referencia
ALTER TABLE ASIGNATURA_MATRICULA DROP FOREIGN KEY FK_ASIGNATURA_MATRICULA_GRUPO_ID
ALTER TABLE JND_Centro_Titulacion DROP FOREIGN KEY FK_JND_Centro_Titulacion_Centro_FK
ALTER TABLE JND_Centro_Titulacion DROP FOREIGN KEY FK_JND_Centro_Titulacion_Titulacion_FK
ALTER TABLE ENCUESTA_GRUPOSPORASIG DROP FOREIGN KEY FK_ENCUESTA_GRUPOSPORASIG_CURSOACADEMICO
ALTER TABLE ENCUESTA_GRUPOSPORASIG DROP FOREIGN KEY ENCUESTAGRUPOSPORASIGcontieneEncuestas_Fecha_Envio
DROP TABLE ALUMNO
DROP TABLE ASIGNATURA
DROP TABLE CENTRO
DROP TABLE CLASE
DROP TABLE ENCUESTA
DROP TABLE EXPEDIENTE
DROP TABLE GRUPO
DROP TABLE GRUPOSPORASIG
DROP TABLE MATRICULA
DROP TABLE TITULACION
DROP TABLE ASIGNATURA_MATRICULA
DROP TABLE JND_Centro_Titulacion
DROP TABLE ENCUESTA_GRUPOSPORASIG
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
