package es.uma.informatica.jpa.demo.tests;

// Generated by Selenium IDE
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;


import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AlumnosIT {
	private static final String UNIDAD_PERSISTENCIA = "SecretariaIT";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar(UNIDAD_PERSISTENCIA);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void insertaralumno() {
    driver.get("http://localhost:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().setSize(new Dimension(1853, 948));
    driver.findElement(By.id("indexIndex:vista-index-alumnos")).click();
    driver.findElement(By.id("indexAl:IndAl-InsertarAl")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-dni")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-dni")).sendKeys("1234");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-nombre")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-nombre")).sendKeys("Erick");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-telefono")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-telefono")).sendKeys("65656565");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-movil")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-movil")).sendKeys("54545454");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-institucional")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-institucional")).sendKeys("erick@uma.es");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-personal")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-personal")).sendKeys("personal@gamil.com");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-boton-crear-alumno")).click();
    driver.findElement(By.id("LiAl-alumnos-id:j_idt8:1:LiAl-dni-alumno")).click();
    driver.findElement(By.id("LiAl-alumnos-id:j_idt8:1:LiAl-dni-alumno")).click();
    {
      WebElement element = driver.findElement(By.id("LiAl-alumnos-id:j_idt8:1:LiAl-dni-alumno"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.id("LiAl-alumnos-id:j_idt8:1:LiAl-dni-alumno")).getText(), is("1234"));
    driver.findElement(By.id("LiAl-alumnos-id:j_idt8:1:LiAl-dni-alumno")).click();
  }
}
