// Generated by Selenium IDE
package es.uma.informatica.jpa.demo.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AsignaturasTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Ignore
  @Requisitos({"RF12"})
  @Test
  public void crudAsignatura() throws InterruptedException {
    driver.get("http://localhost:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().maximize();
    driver.findElement(By.id("indexIndex:vista-index-asignatura")).click();
    driver.findElement(By.id("indexAs:IndAs-insertarAsig")).click();
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-referencia")).sendKeys("25");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-Codigo_Asignatura")).sendKeys("21345");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-creditos")).sendKeys("22334");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-ofertada")).sendKeys("si");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-nombre")).sendKeys("r");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-curso")).sendKeys("2");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-caracter")).sendKeys("c");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-duracion")).sendKeys("231");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-unidadTemporal")).sendKeys("2");
    driver.findElement(By.id("InsAs-InsertarAsig:InsRef-idiomasImparticion")).sendKeys("3");
    driver.findElement(By.id("InsAs-InsertarAsig:InsAs-BotonCrearAsig")).click();
    assertTrue("No existe la asignatura", driver.getPageSource().contains("25"));
    driver.findElement(By.id("LiAsi-asignaturas-id:j_idt10:0:LiAsi-ModificarC2")).click();
    
    driver.findElement(By.id("EdAs-EditarAs:EdAs-nombre")).clear();
    
    driver.findElement(By.id("EdAs-EditarAs:EdAs-nombre")).sendKeys("riiiii");
    driver.findElement(By.cssSelector("a:nth-child(13)")).click();
    driver.findElement(By.cssSelector("td:nth-child(5)")).click();
    assertThat(driver.findElement(By.id("LiAsi-asignaturas-id:j_idt10:0:LiAsi-NombreC2")).getText(), is("riiiii"));
    driver.findElement(By.id("LiAsi-asignaturas-id:j_idt10:0:LiAsi-EliminarC2")).click();
    Thread.sleep(8000);
    assertThat(driver.switchTo().alert().getText(), is("ASIGNATURA BORRADA"));
    driver.switchTo().alert().accept();
    Thread.sleep(4000);
  }
}
