package es.uma.informatica.jpa.demo.tests;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExpedientesTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void crudExpediente() throws InterruptedException {
    driver.get("http://localhost:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().maximize();
    driver.findElement(By.id("indexIndex:vista-index-alumnos")).click();
    driver.findElement(By.id("indexAl:IndAl-InsertarAl")).click();
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-dni")).sendKeys("666c");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-nombre")).sendKeys("risha");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-telefono")).sendKeys("99999");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-movil")).sendKeys("88888");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-institucional")).sendKeys("a@a");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-email-personal")).sendKeys("b@b");
    driver.findElement(By.id("InsAl-insertar-alumno:InsAl-boton-crear-alumno")).click();
    Thread.sleep(4000);
    driver.findElement(By.id("LiAl-alumnos-id:j_idt11:1:LiAl-boton-modificar-alumno")).click();
    driver.findElement(By.cssSelector("a:nth-child(10)")).click();
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-numExpediente")).sendKeys("123456789");
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-Nota_Media_Provisional")).sendKeys("8");
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-BotonCrearExp")).click();
    assertTrue("No existe el expediente", driver.getPageSource().contains("123456789"));
    driver.findElement(By.id("LiExp-expedientes-id:j_idt13:0:LiExp-Modificar")).click();
    
    driver.findElement(By.id("EdEx-EditarEx:EdEx-Nota_Media_Provisional")).clear();
    
    driver.findElement(By.id("EdEx-EditarEx:EdEx-Nota_Media_Provisional")).sendKeys("6");
    driver.findElement(By.cssSelector("a:nth-child(6)")).click();
    driver.findElement(By.cssSelector("td:nth-child(3)")).click();
    assertThat(driver.findElement(By.id("LiExp-expedientes-id:j_idt13:0:LiExp-NotaMediaProvisional")).getText(), is("6"));
    driver.findElement(By.id("LiExp-expedientes-id:j_idt13:0:LiExp-Eliminar")).click();
    Thread.sleep(8000);
    assertThat(driver.switchTo().alert().getText(), is("EXPEDIENTE BORRADO"));
    driver.switchTo().alert().accept();
    Thread.sleep(4000);
    driver.findElement(By.cssSelector("a")).click();
    driver.findElement(By.id("indexEx:IndEx-Index")).click();
    driver.findElement(By.id("indexIndex:vista-index-alumnos")).click();
    driver.findElement(By.id("indexAl:IndAl-ListaAl")).click();
    driver.findElement(By.id("LiAl-alumnos-id:j_idt11:1:LiAl-boton-eliminar-alumno")).click();
    Thread.sleep(8000);
    assertThat(driver.switchTo().alert().getText(), is("ALUMNO BORRADO"));
    driver.switchTo().alert().accept();
    Thread.sleep(4000);
  }
}
