// Generated by Selenium IDE
package es.uma.informatica.jpa.demo.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExpedientesTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Ignore
  @Test
  public void crearexpediente() {
    driver.get("http://localhost:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().maximize();
    driver.findElement(By.id("indexIndex:vista-index-expediente")).click();
    driver.findElement(By.id("indexEx:IndEx-InsertarExp")).click();
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-numExpediente")).click();
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-numExpediente")).sendKeys("123412");
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-Nota_Media_Provisional")).click();
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-Nota_Media_Provisional")).sendKeys("8");
    driver.findElement(By.id("InsEx-InsertarExp:InsEx-BotonCrearExp")).click();
    assertThat(driver.findElement(By.id("LiExp-expedientes-id:j_idt10:0:LiExp-NumExp")).getText(), is("123412"));
    assertThat(driver.findElement(By.id("LiExp-expedientes-id:j_idt10:0:LiExp-Activo")).getText(), is("true"));
    assertThat(driver.findElement(By.id("LiExp-expedientes-id:j_idt10:0:LiExp-NotaMediaProvisional")).getText(), is("8"));
    driver.findElement(By.id("LiExp-expedientes-id:j_idt10:0:LiExp-Eliminar")).click();
  }
}
