package es.uma.informatica.jpa.demo.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
public class ImportarAsignaturasIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Requisitos({"RF-08"})
  @Test
  public void untitled() throws InterruptedException {
	File f = new File("Oferta asignaturas.xlsx");
	String absolutePath = f.getAbsolutePath();
	
    driver.get("http://0.0.0.0:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().maximize();
    
    driver.findElement(By.id("indexIndex:vista-index-asignatura")).click();
    driver.findElement(By.id("indexAs:IndAs-insertarAsig")).click();
    WebElement uploadElement = driver.findElement(By.xpath("//input[@id='InsRef-importarAsignaturas:InsRef-file']"));
    uploadElement.sendKeys(absolutePath);
    driver.findElement(By.xpath("//a[contains(text(),\'Enviar Fichero\')]")).click();
    Thread.sleep(4000);
    assertTrue("No existe la asignatura", driver.getPageSource().contains("50661"));
    driver.findElement(By.id("LiAsi-asignaturas-id:LiAsi-EliminarTodas")).click();
    assertThat(driver.switchTo().alert().getText(), is("ASIGNATURAS BORRADAS"));
    driver.switchTo().alert().accept();
    Thread.sleep(4000);
  }
}
