package es.uma.informatica.jpa.demo.tests;

// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TitulacionesTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Ignore
  @Requisitos({"RF17"})
  @Test
  public void crudTitulacion() throws InterruptedException {
    driver.get("http://localhost:8080/jpa.demo-war/faces/index.xhtml");
    driver.manage().window().maximize();
    driver.findElement(By.id("indexIndex:vista-index-titulacion")).click();
    driver.findElement(By.id("indexTi:IndTi-InsertarTi")).click();
    driver.findElement(By.id("InsTit-InsertarTitu:InsTit-codigo")).sendKeys("1059");
    driver.findElement(By.id("InsTit-InsertarTitu:InsTit-nombre")).sendKeys("Ingenieria de rager");
    driver.findElement(By.id("InsTit-InsertarTitu:InsTit-creditos")).sendKeys("66");
    driver.findElement(By.id("InsTit-InsertarTitu:InsTit-BotonCrearTit")).click();
    assertTrue("No existe la titulacion", driver.getPageSource().contains("1059"));
    driver.findElement(By.id("LiTit-titulaciones-id:j_idt10:0:LiTit-ModificarC2")).click();
    
    driver.findElement(By.id("EdTi-EditarTi:EdTi-nombre")).clear();
    
    driver.findElement(By.id("EdTi-EditarTi:EdTi-nombre")).sendKeys("Ingenieria de franci");
    driver.findElement(By.cssSelector("a:nth-child(6)")).click();
    driver.findElement(By.cssSelector("td:nth-child(2)")).click();
    assertThat(driver.findElement(By.id("LiTit-titulaciones-id:j_idt10:0:LiTit-NombreC2")).getText(), is("Ingenieria de franci"));
    driver.findElement(By.id("LiTit-titulaciones-id:j_idt10:0:LiTit-EliminarC2")).click();
    Thread.sleep(8000);
    assertThat(driver.switchTo().alert().getText(), is("TITULACION BORRADA"));
    driver.switchTo().alert().accept();
    Thread.sleep(4000);
  }
}
